# https://taskfile.dev

version: '3'

vars:
  MODULE_NAME: sample
  SRC_DIR: ./src/main/go/batch
  TEST_DIR: ./src/test/go/batch
  BINARY_NAME: batch
  BUILD_OUTPUT_DIR: dist

tasks:
  test:
    desc: "Run test for the batch package."
    cmds:
      - go test {{.MODULE_NAME}}/src/test/go/batch/config -v

  build:
    desc: "Build the fetcher executable to {{.BUILD_OUTPUT_DIR}}/"
    deps:
      - copy-jsl # JSLファイルをコピーするタスクを依存関係に追加
    ensures:
      - dir: [".{{.BUILD_OUTPUT_DIR}}"]
    cmds:
      - cp src/main/resources/application.yaml src/main/go/batch/config
      - go build -v -gcflags="all=-N -l" -o {{.BUILD_OUTPUT_DIR}}/{{.BINARY_NAME}} {{.SRC_DIR}}
      - rm src/main/go/batch/config/application.yaml
      - echo "Build executable to {{.BUILD_OUTPUT_DIR}}/{{.BINARY_NAME}}"
    generates:
      - "{{.BUILD_OUTPUT_DIR}}/{{.BINARY_NAME}}"
    sources:
      - "{{.SRC_DIR}}/**/*.go" # Goソースファイル全体を対象に含める
      - src/main/resources/application.yaml
      - src/main/resources/jobs/*.yaml # JSLファイルもソースに含める

  copy-jsl:
    desc: "JSL YAML ファイルを Go の embed ディレクトリにコピーします"
    cmds:
      - mkdir -p src/main/go/batch/job/jsl # ターゲットディレクトリが存在することを確認
      - cp src/main/resources/jobs/*.yaml src/main/go/batch/job/jsl/
    sources:
      - src/main/resources/jobs/*.yaml
    generates:
      - src/main/go/batch/job/jsl/*.yaml

  run:
    desc: "Build and run the application."
    deps: [build]
    cmds:
      - ./{{.BUILD_OUTPUT_DIR}}/{{.BINARY_NAME}}

  clean:
    desc: "Remove build artifacts."
    cmds:
      - rm -rf ./{{.BUILD_OUTPUT_DIR}}
      - rm -f src/main/go/batch/job/jsl/*.yaml # コピーしたJSLファイルを削除
      - rm -f src/main/go/batch/job/weather_job.go # 不要になったファイルを削除

  mod-tidy:
    desc: "Add missing and remove unused go-modules."
    cmds:
      - go clean -modcache
      - go clean -cache -testcache
      - go mod tidy
