# https://taskfile.dev

version: '3'

vars:
  MODULE_NAME: sample
  SRC_DIR: ./src/main/go/batch
  TEST_DIR: ./src/test/go/batch
  BINARY_NAME: batch
  BUILD_OUTPUT_DIR: dist

tasks:
  test:
    desc: "Run test for the batch package."
    cmds:
      - go test {{.MODULE_NAME}}/src/test/go/batch/config -v

  build:
    desc: "Build the fetcher executable to {{.BUILD_OUTPUT_DIR}}/"
    ensures:
      - dir: [".{{BUILD_OUTPUT_DIR}}"]
    cmds:
      - cp src/main/resources/application.yaml src/main/go/batch/config
      - go build -v -o {{.BUILD_OUTPUT_DIR}}/{{.BINARY_NAME}} {{.SRC_DIR}}
      - rm src/main/go/batch/config/application.yaml
      - echo "Build executable to {{.BUILD_OUTPUT_DIR}}/{{.BINARY_NAME}}"
    generates:
      - "{{.BUILD_OUTPUT_DIR}}/{{.BINARY_NAME}}"
    sources:
      - "{{.SRC_DIR}}/*.go"

  run:
    desc: "Build and run the application."
    deps: [build]
    cmds:
      - ./{{.BUILD_OUTPUT_DIR}}/{{.BINARY_NAME}}

  clean:
    desc: "Remove build artifacts."
    cmds:
      - rm -rf ./{{.BUILD_OUTPUT_DIR}}
      - go clean -modcache
      - go clean -cache -testcache
