# https://taskfile.dev

version: '3'

vars:
  MODULE_NAME: sample
  SRC_DIR: example/weather # 変更: アプリケーションのルートディレクトリ
  TEST_DIR: test/batch
  BINARY_NAME: batch
  BUILD_OUTPUT_DIR: dist

tasks:
  test:
    desc: "Run test for the batch package."
    cmds: # testディレクトリ以下の全てのテストを実行するように変更
      - go test ./test/... -v

  build:
    desc: "Build the fetcher executable to {{.BUILD_OUTPUT_DIR}}/"
    ensures:
      - dir: [".{{.BUILD_OUTPUT_DIR}}"]
    cmds:
      - go build -v -gcflags="all=-N -l" -o {{.BUILD_OUTPUT_DIR}}/{{.BINARY_NAME}} {{.MODULE_NAME}}/{{.SRC_DIR}} # モジュールパスで指定
      - echo "Build executable to {{.BUILD_OUTPUT_DIR}}/{{.BINARY_NAME}}"
    generates:
      - "{{.BUILD_OUTPUT_DIR}}/{{.BINARY_NAME}}"
    sources:
      - "{{.SRC_DIR}}/**/*.go" # Goソースファイル全体を対象に含める
      - "{{.SRC_DIR}}/resources/application.yaml" # 埋め込み対象のapplication.yamlをソースに含める
      - "{{.SRC_DIR}}/resources/job.yaml" # JSLファイルもソースに含める (main.go で embed するため)

  run:
    desc: "Build and run the application."
    deps: [build]
    cmds:
      - ./{{.BUILD_OUTPUT_DIR}}/{{.BINARY_NAME}}

  clean:
    desc: "Remove build artifacts."
    cmds:
      - rm -rf ./{{.BUILD_OUTPUT_DIR}}

  mod-tidy:
    desc: "Add missing and remove unused go-modules."
    cmds:
      - go clean -modcache
      - go clean -cache -testcache
      - go mod tidy
